import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image';

import PageHeader from '../components/PageHeader';
import ProductCard from '../components/__molecules__/ProductCard';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader />
      <main className={styles.main}>
        <ProductCard
            name="Red Bench"
          category="people"
          price={3.89}
          currency="USD"
          isBestseller
          isFeatured={false}
            image={{
                src: 'https://images.pexels.com/photos/57690/pexels-photo-57690.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
                alt: 'image',
            }}
        />
      </main>
    </div>
  )
}

export default Home
